server:
  port: 8085
spring:
  application:
    name: kitchen
  profiles:
    active: rabbitmq-listener
---
spring:
  config:
    activate:
      on-profile: jms-template, jms-listener
  jms:
    template:
      receive-timeout: 2
  artemis:
    host: localhost
    port: 61617
    user: admin
    password: password
    embedded:
      enabled: false
debug: true
queue:
  name: tacocloud.order.queue
---
spring:
  config:
    on-profile: rabbitmq-template, rabbitmq-listener
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: ja09091990
queue:
  name: kitchen.central